apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "customer-service"
        dapr.io/app-port: "8000"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
        dapr.io/http-port: "3510"
    spec:
      containers:
      - name: customer-service
        image: customer-service:1.0
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_USER
            value: "customer_service"
          - name: POSTGRES_PASSWORD
            value: "customer_service_pass"
          - name: POSTGRES_HOST
            value: "customer-db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "customer_service"
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]