# apiVersion: v1
# kind: Service
# metadata:
#   name: zipkin
#   namespace: monitoring
# spec:
#   selector:
#     app: zipkin
#   ports:
#     - port: 9411
#       targetPort: 9411
#   type: ClusterIP
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zipkin
spec:
  type: exporters.zipkin
  version: v1
  metadata:
    - name: endpoint
      value: http://localhost:9411/api/v2/spans