name: CI/CD Pipeline

on:
  push:
    branches:
      - network_administration_and_services
  pull_request:
    branches:
      - network_administration_and_services

jobs:
  build-and-deploy:
    name: Build and Deploy Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service_dir:
          - "src/Customer Service"
          - "src/Report Service"
          - "src/Sales Service"
        container_name:
          - "customer-service"
          - "reporting-service"
          - "app"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate .env File
        run: |
            if [[ "${{ matrix.service_dir }}" == "src/Customer Service" ]]; then
              echo "${{ secrets.CUSTOMER_SERVICE_ENV }}" > "${{ matrix.service_dir }}/.env"
            elif [[ "${{ matrix.service_dir }}" == "src/Report Service" ]]; then
              echo "${{ secrets.REPORT_SERVICE_ENV }}" > "${{ matrix.service_dir }}/.env"
            fi

      - name: Build and Push Docker Image
        run: |
          SERVICE_DIR="${{ matrix.service_dir }}"
          CONTAINER_NAME="${{ matrix.container_name }}"
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${CONTAINER_NAME}"
          cd "${SERVICE_DIR}"
          docker build -t ${IMAGE_NAME}:latest .
          docker push ${IMAGE_NAME}:latest